[tool.poetry]
name = "girg-sampling"
version = "0.1.0"
description = "Efficient sampling of geometric inhomogeneous random graphs (GIRG), a C++ lib wrapper."
authors = ["Tomas Gavenciak <gavento@gmail.com>"]
build = "build.py"
packages = [
    { include = "girg_sampling" },
]

[tool.poetry.dependencies]
python = ">=3.6.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
black = "^20.8b1"
pre-commit = "^2.7.1"
cmaketools = "^0.1.6"
wheel = "^0.35.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
