name: Build and test package

on:
  push:
  release:
    types: [published]

jobs:
  lint_build_test:
    name: Lint, build and test on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache the environment
        uses: actions/cache@v2
        with:
          path: |
            .env
            .poetry
            .cache/pre-commit
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install and configure poetry
        run: |
          python get-poetry.py -y
          source $HOME/.poetry/env
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config cache-dir ~/.poetry/cache
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry -V
      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install --no-root
      - name: Lint with pre-commit
        run: |
          source $HOME/.poetry/env
          poetry run pre-commit run --all-files
      - name: Build and install the library
        run: |
          source $HOME/.poetry/env
          poetry build
          poetry run pip install dist/girg_sampling-*.whl
      - name: Test with pytest
        run: |
          source $HOME/.poetry/env
          poetry run pytest

      - name: Publish with poetry to TestPyPI
        if: ${{ github.event_name == 'release' }}
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{secrets.TESTPYPI_TOKEN}}
        run: |
          source $HOME/.poetry/env
          poetry publish -r testpypi

      - name: Publish with poetry to PyPI
        if: ${{ github.event_name == 'release' }}
        # Note: && github.event.action == 'published' }}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.PYPI_TOKEN}}
        run: |
          source $HOME/.poetry/env
          poetry publish
